### PR TITLE
Release process

### PR DESCRIPTION
**Pull request by steven-collins-omega**
This PR defines a release process, and then partially follows it up to making a commit with the release number as the commit message. Once the PR is approved I'll tag that commit and make an official GitHub release.

### CODE REVIEW

**Comment by steven-collins-omega** [comment]
Making this a draft until I decide how to deal with the issue of counterfeiter being deleted by `go mod tidy` (a decision I will timebox)

**Comment by steven-collins-omega** [comment]
@ScarletTanager Now ready for review. Since the original proposed v0.1.0 was not a viable release, I've simply proposed a new initial public release v0.1.1 . Following the current proposed RELEASING.md, what I have here in this PR is up through step 3 ("Create a commit...")

**Comment by ScarletTanager** [comment]
@steven-collins-omega please squash these commits into a single commit (`git rebase -s <last commit hash *before* your commits>`, then force push to your branch).

**Review by ScarletTanager — APPROVED** [review]
Looks good to me.

**Pull request merged**
